sudo: required
services:
  - xvfb
language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
install:
  - npm ci

addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable fluxbox

# Deployments
deploy:
  - provider: heroku #Deploy for Heroku
    api_key: $HEROKU_API_KEY
    app: service-go
    on:
      repo: sharad-ghimire/service-go
  - provider: azure_web_apps #Deploy to Azure
    username: $AZURE_WA_USERNAME
    password: $AZURE_WA_PASSWORD
    site: $AZURE_WA_SITE
    on:
      branch: master

# Slack Notification Integraion
notifications:
  slack:
    rooms:
      - asdmates:la4VlTSI29ezy3xcJf7j8vuT
    on_success: always
    on_failure: always
    on_start: never
